export const contributeUI = {
  en: {
    // Meta
    'contribute.meta.title': 'I Want to Contribute — Taiwan.md',
    'contribute.meta.description':
      'No programming skills needed. You can help the world understand Taiwan',

    // Hero Section
    'contribute.hero.title': 'I Want to Contribute ✋',
    'contribute.hero.subtitle':
      'No programming skills needed. Your Taiwan stories are the most valuable content.',
    'contribute.hero.note.html':
      'Current website content is initially generated by AI, expecting everyone to join forces to make information more complete and accurate!<br />If you have any questions, please feel free to <a href="mailto:cheyu.wu@monoame.com" style="color: #ABC468;">contact us</a>. Thank you for your thoughtful feedback!',

    // How It Works Section
    'contribute.how.title': '🗺️ First, understand how this website works',
    'contribute.how.language.icon': '📁',
    'contribute.how.language.title': 'Language Toggle',
    'contribute.how.language.desc.html':
      'Toggle between <strong>Chinese</strong> and <strong>English</strong> in the top-right corner. Chinese is the primary content (SSOT), English is being translated continuously.',
    'contribute.how.language.code.html':
      'taiwan.md/ → Chinese<br />taiwan.md/en/ → English',
    'contribute.how.md.icon': '📝',
    'contribute.how.md.title': '.md Button',
    'contribute.how.md.desc.html':
      "The floating <strong>.md</strong> button in the bottom-right corner of each page shows the original Markdown file. All Taiwan.md content is plain text Markdown — that's where the .md domain comes from.",
    'contribute.how.graph.icon': '🕸️',
    'contribute.how.graph.title': 'Knowledge Graph',
    'contribute.how.graph.desc':
      'The "Graph" link in the navigation leads to an interactive knowledge network diagram. Drag to explore connections between 12 aspects.',
    'contribute.how.ai.icon': '🤖',
    'contribute.how.ai.title': 'AI-Friendly',
    'contribute.how.ai.desc.html':
      'All content is fully open to AI crawlers (<a href="/robots.txt">robots.txt</a>, <a href="/llms.txt">llms.txt</a>). Feel free for ChatGPT / Claude / Gemini to cite.',

    // Roles Section
    'contribute.roles.title': "Your expertise is Taiwan's needed strength",
    'contribute.roles.desc':
      'No matter your background, you can bring unique value to this knowledge base',

    // Role: Writer
    'contribute.roles.writer.icon': '✍️',
    'contribute.roles.writer.title': 'Writers / Editors',
    'contribute.roles.writer.desc':
      'Your writing skills are the core of the knowledge base. Write new articles, improve readability of existing content, proofread typos and sentences.',
    'contribute.roles.writer.action1':
      "→ Pick a topic you're familiar with and write a warm article",
    'contribute.roles.writer.action2':
      '→ Help polish existing articles and add details',

    // Role: Researcher
    'contribute.roles.researcher.icon': '🔬',
    'contribute.roles.researcher.title': 'Researchers / Scholars',
    'contribute.roles.researcher.desc':
      'Your professional knowledge is a quality guarantee. Fact-check, add academic perspectives, point out common misconceptions.',
    'contribute.roles.researcher.action1':
      '→ Review facts and citations in articles',
    'contribute.roles.researcher.action2':
      '→ Add in-depth content from your research field',

    // Role: Designer
    'contribute.roles.designer.icon': '🎨',
    'contribute.roles.designer.title': 'Designers',
    'contribute.roles.designer.desc':
      'Good information needs good presentation. Infographics, SVG illustrations, and UI/UX improvements are all huge contributions.',
    'contribute.roles.designer.action1':
      '→ Create infographics or diagrams for articles',
    'contribute.roles.designer.action2.html':
      '→ Contribute Taiwan-themed open source icons to <a href="/en/assets">SVG Asset Library</a>',

    // Role: Engineer
    'contribute.roles.engineer.icon': '💻',
    'contribute.roles.engineer.title': 'Engineers',
    'contribute.roles.engineer.desc':
      'The website itself needs evolution. Performance optimization, new features, i18n, accessibility, SEO are all welcome.',
    'contribute.roles.engineer.action1.html':
      '→ Check if there\'s anything you can solve in <a href="https://github.com/frank890417/taiwan-md/issues" target="_blank">GitHub Issues</a>',
    'contribute.roles.engineer.action2':
      '→ Improve search, graph, multilingual features',

    // Role: Translator
    'contribute.roles.translator.icon': '🌍',
    'contribute.roles.translator.title': 'Translators',
    'contribute.roles.translator.desc':
      "Help the world understand Taiwan. Paste our AI prompt, translate one article, open a PR. Your AI subscription = one compute node in our distributed translation network.",
    'contribute.roles.translator.action1.html':
      '→ See what needs translating on <a href="https://github.com/frank890417/taiwan-md/blob/main/TRANSLATION-BOARD.md">Translation Board</a>',
    'contribute.roles.translator.action2':
      '→ 4 languages live (en/es/ja), 7+ more welcome — you could be the first!',

    // Role: Photographer
    'contribute.roles.photographer.icon': '📸',
    'contribute.roles.photographer.title': 'Photographers / Creators',
    'contribute.roles.photographer.desc':
      'A good photo is worth a thousand words. CC-licensed Taiwan photos, field recordings, and media materials are much needed.',
    'contribute.roles.photographer.action1':
      '→ Photograph Taiwan through your eyes, contribute with CC license',
    'contribute.roles.photographer.action2.html':
      '→ Record Taiwan sounds, join the <a href="https://github.com/frank890417/taiwan-md/tree/main/assets/sounds" target="_blank">soundscape project</a>',

    // Role: Cultural Worker
    'contribute.roles.cultural.icon': '🏛️',
    'contribute.roles.cultural.title': 'Cultural Workers / Local Experts',
    'contribute.roles.cultural.desc':
      'Your local knowledge is something AI can never generate. Oral history, local stories, cultural contexts — these are the most valuable content.',
    'contribute.roles.cultural.action1':
      "→ Write down your hometown stories, the kind textbooks don't teach",
    'contribute.roles.cultural.action2': '→ Correct local errors in articles',

    // Role: Anyone
    'contribute.roles.anyone.icon': '📢',
    'contribute.roles.anyone.title': 'Anyone who cares about Taiwan',
    'contribute.roles.anyone.desc':
      'Even if none of the above fits you, your sharing is contribution itself. Forward to friends, mention on social media, give us feedback.',
    'contribute.roles.anyone.action1':
      '→ Share taiwan.md with friends who want to understand Taiwan',
    'contribute.roles.anyone.action2':
      '→ See errors? Open an issue and tell us',

    // Organizations Section
    'contribute.org.title': '🏢 Institutions, Government Agencies & Companies',
    'contribute.org.desc':
      "Taiwan.md welcomes various organizations to participate in different ways, jointly building Taiwan's digital knowledge infrastructure.",

    // Org: Government
    'contribute.org.government.icon': '🏛️',
    'contribute.org.government.title': 'Government Agencies / Public Sector',
    'contribute.org.government.desc':
      'Provide official open data, statistics, policy documents. Help with fact-checking and content correction. License government publications or CC-licensed images.',
    'contribute.org.government.example':
      'Examples: Ministry of Culture, Tourism Bureau, Council of Indigenous Peoples, Ministry of Agriculture, Institute of History',

    // Org: Academic
    'contribute.org.academic.icon': '🎓',
    'contribute.org.academic.title': 'Academic Institutions / Research Units',
    'contribute.org.academic.desc':
      'Help write or review articles in professional fields. Provide research data and academic perspectives. Recommend students to use Taiwan.md as an open knowledge practice field.',
    'contribute.org.academic.example':
      'Examples: Academia Sinica, University Taiwan Studies Departments, Museums, Cultural Studios',

    // Org: Corporate
    'contribute.org.corporate.icon': '🏢',
    'contribute.org.corporate.title': 'Companies / Commercial Organizations',
    'contribute.org.corporate.desc':
      'Sponsor operations (servers, translation, community events). Display branding as Gold / Silver / Bronze Sponsor. Encourage employees to participate as volunteers.',
    'contribute.org.corporate.example':
      'Examples: Tech companies, Publishers, Cultural foundations, International corporate CSR',

    // Org: NGO
    'contribute.org.ngo.icon': '🌏',
    'contribute.org.ngo.title': 'NGO / International Organizations',
    'contribute.org.ngo.desc':
      'Help with multilingual translation and international promotion. Provide local perspectives on human rights, environment, social issues. Use Taiwan.md as international education resource.',
    'contribute.org.ngo.example':
      'Examples: Taiwan Foundation for Democracy, Cultural exchange associations, Overseas Taiwanese communities',

    // Org Contact
    'contribute.org.contact.title': 'Partnership Contact:',
    'contribute.org.contact.email': 'cheyu.wu@monoame.com',
    'contribute.org.contact.subject':
      'Please include "Taiwan.md Partnership — [Organization Name]" in subject line',
    'contribute.org.contact.note':
      'We will respond within 3 business days. Any form of partnership proposal is welcome.',

    // Writing Guides Section
    'contribute.guides.title': '📖 Complete Contribution Guide',
    'contribute.guides.desc':
      'No matter your background and expertise, we have the most suitable contribution method for you',

    // Guide: Writing
    'contribute.guides.writing.icon': '✍️',
    'contribute.guides.writing.title': 'How to Write a Good Article',
    'contribute.guides.writing.belief': '🎯 Core Belief: We Are Not Wikipedia',
    'contribute.guides.writing.belief.desc': 'Taiwan.md is a curated space, not an encyclopedia. We don\'t aim for completeness — we aim for every article to make readers think "Oh, I see!" A good Taiwan.md article makes you want to tell your friends: "Hey, did you know..."',
    'contribute.guides.writing.ironlaws': '🛡️ Three Iron Laws',
    'contribute.guides.writing.ironlaws.story': '<strong>Have Stories, Not Just Information</strong> — Dates, numbers, and names are just the skeleton. Narrative is the flesh and blood.',
    'contribute.guides.writing.ironlaws.verify': '<strong>Every Fact Must Be Verifiable</strong> — Data without sources is worse than no data.',
    'contribute.guides.writing.ironlaws.density': '<strong>Density Over Length</strong> — An 80-line great article > 300-line bullet list, but deep curation with context > compressed-to-lose-meaning summaries.',
    'contribute.guides.writing.core': '⚡ Step 0: Find Your Counter-Intuitive Core',
    'contribute.guides.writing.core.desc': 'Before any research, force yourself to write one sentence: "This article will surprise readers with _____". Good core statements contain contradictions, contrasts, or unexpected elements.',
    'contribute.guides.writing.core.good': '✅ Good examples: "A 30-year-old text-based BBS still influences Taiwan politics today" (time contrast)',
    'contribute.guides.writing.core.bad': '❌ Bad: "Taiwan has a good healthcare system" (no contrast = no attraction)',
    'contribute.guides.writing.openings': '🚀 Four Opening Modes',
    'contribute.guides.writing.openings.scene': '<strong>Scene Opening:</strong> "In September 1995, in a dorm room at NTU..."',
    'contribute.guides.writing.openings.data': '<strong>Data Impact:</strong> "214 weeks — that\'s how long Tai Tzu-ying was world No. 1"',
    'contribute.guides.writing.openings.contrast': '<strong>Contrast Opening:</strong> "A platform that doesn\'t sell ads or accept commercial deals has survived 30 years"',
    'contribute.guides.writing.openings.challenge': '<strong>Challenge Opening:</strong> "Why do 65% of the world\'s chips pass through one island?"',
    'contribute.guides.writing.voice': '🎙️ Curator\'s Voice (Not "Objective" Excuse)',
    'contribute.guides.writing.voice.desc': 'Good curation has rhythm — dense fact sections → breathing space → dense again. Every 2-3 paragraphs, insert a "curator\'s voice" sentence that creates a moment of understanding.',
    'contribute.guides.writing.voice.good': '✅ Good: "This decision seemed insignificant at the time, but looking back, it changed everything."',
    'contribute.guides.writing.voice.bad': '❌ Bad: "This is very significant." (empty)',
    'contribute.guides.writing.research': '🔍 Research Standards',
    'contribute.guides.writing.research.sources': '<strong>5+ independent sources</strong> (different websites/institutions)',
    'contribute.guides.writing.research.primary': '<strong>2+ primary sources</strong> (official docs, interviews, statistics)',
    'contribute.guides.writing.research.english': '<strong>1+ English source</strong> (international perspective)',
    'contribute.guides.writing.research.surprise': '<strong>1 surprising discovery</strong> — if nothing surprises you, research deeper',
    'contribute.guides.writing.blacklist': '🚫 Banned Plastic Phrases',
    'contribute.guides.writing.blacklist.desc': 'These AI-favorite phrases are completely banned. Use natural, conversational language instead:',
    'contribute.guides.writing.blacklist.patterns': '❌ "Not just X, but Y" • "Not only X, but also Y" • "Worth mentioning" • "In fact" • "Without doubt" • "Embodies the spirit of..."',
    'contribute.guides.writing.blacklist.structures': '❌ Excessive parallel sentences (3+ = plastic) • Every paragraph starting with transition words • Fixed ending formulas',
    'contribute.guides.writing.example': '💡 Example: Before & After',
    'contribute.guides.writing.example.html':
      '<div class="example-comparison"><div class="bad-example"><h5>❌ Bad (Typical AI Template)</h5><pre>Tai Tzu-ying is a famous Taiwanese badminton player who has performed excellently in international competitions, winning numerous important awards and bringing glory to Taiwan. Her success has inspired countless young people, making her an important figure in Taiwan sports.</pre></div><div class="good-example"><h5>✅ Good (Story + Data + Humanity)</h5><pre>In 2018, Tai Tzu-ying reached world No. 1 and stayed there for 214 weeks — the longest consecutive streak in women\'s badminton history.\n\nBut what Taiwanese remember most might not be any victory, but her tears after losing the 2020 Tokyo Olympics gold medal match to Chen Yu-fei. That night, "Tai Tzu-ying" topped Google Taiwan search trends.\n\nShe plays left-handed with a style described as "magician" — so many deceptive shots that opponents can\'t guess the next direction.</pre></div></div>',

    // Guide: AI
    'contribute.guides.ai.icon': '🤖',
    'contribute.guides.ai.title': 'AI-Assisted Contribution',
    'contribute.guides.ai.onerule': '🎯 One Golden Rule',
    'contribute.guides.ai.onerule.desc': '<strong>AI is not the author, you are the curator.</strong> AI\'s biggest trap: "knowing a little and starting to make things up." Taiwan.md\'s approach: collect quality sources first, then curate an article from them.',
    'contribute.guides.ai.correct': '✅ Correct Usage',
    'contribute.guides.ai.correct.research': '<strong>AI helps you research</strong> → You curate the story',
    'contribute.guides.ai.correct.sources': '<strong>AI finds sources</strong> → You verify and cross-check',
    'contribute.guides.ai.correct.structure': '<strong>AI suggests structure</strong> → You add the curator\'s voice',
    'contribute.guides.ai.wrong': '❌ Wrong Usage',
    'contribute.guides.ai.wrong.generate': 'Ask AI to "generate an article about Taiwan X" without research',
    'contribute.guides.ai.wrong.trust': 'Trust AI-provided facts without verification',
    'contribute.guides.ai.wrong.copy': 'Copy AI output directly without adding personal curation',
    'contribute.guides.ai.prompt': '📋 One-Click Copy Prompt',
    'contribute.guides.ai.prompt.text':
      'Read the complete content of https://raw.githubusercontent.com/frank890417/taiwan-md/main/CONTRIBUTE_PROMPT.md and then guide me step by step to contribute an article to Taiwan.md following those instructions.',
    'contribute.guides.ai.prompt.features': '🚀 This prompt will auto-read latest guidelines, analyze content gaps, guide you through research, and help you write curator-level articles.',

    // Guide: Translation
    'contribute.guides.translation.icon': '🌍',
    'contribute.guides.translation.title': 'Translation Guide',
    'contribute.guides.translation.priority': '🥇 PR-First Workflow',
    'contribute.guides.translation.priority.desc': 'Translation is now fully systematized. Use our AI-powered workflow for best results.',
    'contribute.guides.translation.board': '📋 Translation Board + AI Prompt',
    'contribute.guides.translation.board.check': '<strong>Check the board:</strong> <a href="https://github.com/frank890417/taiwan-md/blob/main/TRANSLATION-BOARD.md">TRANSLATION-BOARD.md</a> shows exactly what needs translating',
    'contribute.guides.translation.board.prompt': '<strong>Copy the prompt:</strong> <a href="https://github.com/frank890417/taiwan-md/blob/main/TRANSLATE_PROMPT.md">TRANSLATE_PROMPT.md</a> — paste to your AI and it guides you through everything',
    'contribute.guides.translation.board.submit': '<strong>Submit via PR:</strong> AI helps you create PR-ready Markdown files',
    'contribute.guides.translation.languages': '🌏 Expanding Beyond English',
    'contribute.guides.translation.languages.live': '<strong>Live:</strong> English, Español, 日本語, 한국어',
    'contribute.guides.translation.languages.coming': '<strong>Coming:</strong> Français, Deutsch, Tiếng Việt, Bahasa Indonesia, ภาษาไทย, العربية',
    'contribute.guides.translation.languages.you': '<strong>Your language not here?</strong> You could be the first! Just pick a language code and start.',
    'contribute.guides.translation.token': '💡 Token Donation Concept',
    'contribute.guides.translation.token.desc': 'Got unused Claude/ChatGPT/Gemini credits? Spend 10 minutes adding a language version to Taiwan.md. Your AI subscription = one compute node in our distributed translation network.',
    'contribute.guides.translation.quality': '⚡ Quality: Rewriting vs. Word-for-Word',
    'contribute.guides.translation.quality.rewrite': '<strong>Rewrite approach:</strong> Make it sound like a native speaker wrote it from scratch',
    'contribute.guides.translation.quality.context': '<strong>Add context:</strong> Explain Taiwan-specific concepts for international readers',
    'contribute.guides.translation.quality.style': '<strong>Maintain style:</strong> Keep the curator\'s voice and emotional arc',
    'contribute.guides.translation.quality.verify': '<strong>Always verify:</strong> AI can hallucinate facts, especially Taiwan-specific details',

    // Guide: Images
    'contribute.guides.images.icon': '📸',
    'contribute.guides.images.title': 'Image Guidelines',
    'contribute.guides.images.priority': '🥇 Wikimedia Commons Priority',
    'contribute.guides.images.priority.desc': 'Start here first — massive collection of Taiwan-related CC images with clear licensing.',
    'contribute.guides.images.priority.search': '<strong>Search tip:</strong> Use Wikimedia Commons API or browse <a href="https://commons.wikimedia.org/wiki/Category:Taiwan" target="_blank">Taiwan categories</a> before anywhere else.',
    'contribute.guides.images.acceptable': '✅ Acceptable Sources (In Order)',
    'contribute.guides.images.wikimedia.html':
      '<strong>1. Wikimedia Commons:</strong> First choice — verified CC licensing, high quality',
    'contribute.guides.images.government.html':
      '<strong>2. Government open data:</strong> <a href="https://data.gov.tw/" target="_blank">data.gov.tw</a> and ministry websites',
    'contribute.guides.images.selftaken.html':
      '<strong>3. Self-taken:</strong> Your own photography with clear CC licensing declaration',
    'contribute.guides.images.forbidden': '❌ Forbidden Sources',
    'contribute.guides.images.forbidden.unsplash': '<strong>Unsplash:</strong> ❌ License risks — stick to Wikimedia Commons',
    'contribute.guides.images.forbidden.google': '<strong>Google Images:</strong> ❌ Copyright unknown',
    'contribute.guides.images.forbidden.social': '<strong>Social media:</strong> ❌ Others\' photos without permission',
    'contribute.guides.images.forbidden.commercial': '<strong>Stock photos:</strong> ❌ Unless you own license',
    'contribute.guides.images.format': '📝 Attribution Format',
    'contribute.guides.images.format.html':
      '<pre><code>![Alt text describing the image](image_url)\n\n*Caption: Brief description of what this shows*\n*Source: [Wikimedia Commons](exact_file_url) / CC BY-SA 4.0*</code></pre>',
    'contribute.guides.images.standards': '⚙️ Technical Standards',
    'contribute.guides.images.standards.size': '<strong>Resolution:</strong> 800-1200px width for web display',
    'contribute.guides.images.standards.format': '<strong>Format:</strong> JPG for photos, PNG for graphics, SVG for simple illustrations',
    'contribute.guides.images.standards.alt': '<strong>Alt text:</strong> Always provide descriptive alt text for accessibility',

    // Guide: Quality Self-Check
    'contribute.guides.quality.icon': '✅',
    'contribute.guides.quality.title': 'Pre-Submission Self-Check',
    'contribute.guides.quality.desc': 'Before submitting, run through this 5-point checklist to avoid common rejection reasons:',
    'contribute.guides.quality.checklist': '🔍 5-Point Quality Checklist',
    'contribute.guides.quality.checklist.counter': '<strong>1. Counter-intuitive core:</strong> Can you point to the one thing that will surprise readers?',
    'contribute.guides.quality.checklist.opening': '<strong>2. Strong opening:</strong> Do your first 3 sentences contain specific facts (dates/numbers/names)?',
    'contribute.guides.quality.checklist.sources': '<strong>3. Verifiable sources:</strong> Can readers click links to verify your key claims?',
    'contribute.guides.quality.checklist.voice': '<strong>4. Curator\'s voice:</strong> Is there at least one sentence that could work as a tweet?',
    'contribute.guides.quality.checklist.challenges': '<strong>5. Challenges included:</strong> Did you mention controversies/limitations, not just positives?',
    'contribute.guides.quality.rejections': '🚫 Common Rejection Reasons',
    'contribute.guides.quality.rejections.plastic': '<strong>Plastic language:</strong> "Taiwan is not just X, but also Y" or "Worth mentioning"',
    'contribute.guides.quality.rejections.bullets': '<strong>Bullet list abuse:</strong> 4+ consecutive bullet points instead of narrative',
    'contribute.guides.quality.rejections.sources': '<strong>No sources:</strong> Claims without clickable verification links',
    'contribute.guides.quality.rejections.neutral': '<strong>Wikipedia tone:</strong> Sounds like an encyclopedia entry, not human curation',
    'contribute.guides.quality.script': '🤖 Automated Check',
    'contribute.guides.quality.script.desc': 'Our detect-ai-hollow.sh script automatically flags articles with scores >3. Aim for ≤3 for auto-acceptance.',

    // Paths Section
    'contribute.paths.title': 'Choose your way',

    // Path: Easy
    'contribute.paths.easy.badge': '🟢 Easiest',
    'contribute.paths.easy.title': 'Just fill out a form',
    'contribute.paths.easy.desc.html':
      "Write down what you know. A story, a fun fact, the origin of a dish.<br />We'll help with formatting, translation, and publishing.",
    'contribute.paths.easy.feature1': '✅ No account needed',
    'contribute.paths.easy.feature2': '✅ No need to know Markdown',
    'contribute.paths.easy.feature3': '✅ Can upload photos and documents',
    'contribute.paths.easy.feature4': '✅ Anonymous or credited, your choice',
    'contribute.paths.easy.button': 'Start filling ↓',

    // Path: Medium
    'contribute.paths.medium.badge': '🟡 Some barrier',
    'contribute.paths.medium.title': 'Send it to us',
    'contribute.paths.medium.desc':
      'Already have existing articles, PDFs, or photos? Send them directly.',
    'contribute.paths.medium.email.html':
      '📧 Email: <a href="mailto:cheyu.wu@monoame.com">cheyu.wu@monoame.com</a>',
    'contribute.paths.medium.github': '💬 GitHub Discussion (Chinese OK)',
    'contribute.paths.medium.button': 'Send Email →',

    // Path: AI
    'contribute.paths.ai.badge': '🤖 Let AI help you',
    'contribute.paths.ai.title': 'Talk to your AI',
    'contribute.paths.ai.desc':
      'Paste the following to ChatGPT, Claude, or Gemini, and your AI will guide you step by step to complete your contribution:',
    'contribute.paths.ai.prompt':
      'I want to contribute content to Taiwan.md (taiwan.md) open Taiwan knowledge base. Please first read https://taiwan.md/llms.txt and https://taiwan.md/contributing to understand the project structure and editorial guidelines, then guide me step by step to turn my Taiwan knowledge into a Markdown article. The topic I want to write about is: ______',
    'contribute.paths.ai.feature1': '✅ No programming skills needed',
    'contribute.paths.ai.feature2': '✅ AI will help format into Markdown',
    'contribute.paths.ai.feature3':
      '✅ Can submit via Email or PR after completion',
    'contribute.paths.ai.feature4': '✅ Supports any AI assistant',
    'contribute.paths.ai.fullprompt': 'View Full Prompt →',

    // Path: Dev
    'contribute.paths.dev.badge': '🔴 Developers',
    'contribute.paths.dev.title': 'Fork & PR',
    'contribute.paths.dev.desc.html':
      'You know Git? Great. Just add articles directly in the <code>knowledge/</code> directory.',
    'contribute.paths.dev.guide.html':
      '📖 <a href="/en/contributing">Contributing Guidelines</a>',
    'contribute.paths.dev.editorial.html':
      '📝 <a href="https://github.com/frank890417/taiwan-md/blob/main/EDITORIAL.md" target="_blank">Editorial Guidelines</a>',
    'contribute.paths.dev.button': 'Go to GitHub →',

    // Form Section
    'contribute.form.title': '📝 Share your Taiwan knowledge',
    'contribute.form.desc':
      "Fill in as much or as little as you want. One sentence is fine, a whole article is great. We'll take care of turning it into a beautiful article.",
    'contribute.form.content.label': 'What do you want to share?',
    'contribute.form.content.required': '*',
    'contribute.form.content.placeholder':
      "A story, a fun fact, the origin of a dish, the history of a place... anything goes.\n\nFor example: 'My grandma is from Changhua, she said that every Mid-Autumn Festival...'",
    'contribute.form.category.label': 'Which aspect does this belong to?',
    'contribute.form.category.unsure': "Not sure (we'll categorize it)",
    'contribute.form.category.history': '📜 History',
    'contribute.form.category.geography': '🗺️ Geography',
    'contribute.form.category.culture': '🎭 Culture',
    'contribute.form.category.food': '🍜 Food',
    'contribute.form.category.art': '🎨 Art',
    'contribute.form.category.music': '🎵 Music',
    'contribute.form.category.technology': '💻 Technology',
    'contribute.form.category.nature': '🌿 Nature',
    'contribute.form.category.people': '👥 People',
    'contribute.form.category.society': '⚖️ Society',
    'contribute.form.category.economy': '📈 Economy',
    'contribute.form.category.lifestyle': '🏠 Lifestyle',
    'contribute.form.sourcetype.label': 'How do you know this?',
    'contribute.form.sourcetype.choose': 'Choose...',
    'contribute.form.sourcetype.experience': 'Personal experience',
    'contribute.form.sourcetype.family': 'Family oral history',
    'contribute.form.sourcetype.book': 'Books',
    'contribute.form.sourcetype.internet': 'Internet',
    'contribute.form.sourcetype.professional': 'Professional background',
    'contribute.form.sourcetype.other': 'Other',
    'contribute.form.sourceref.label': 'Reference source',
    'contribute.form.sourceref.placeholder': 'Link, book title, or any clue',
    'contribute.form.name.label': 'Your name',
    'contribute.form.name.placeholder':
      "Fill if you want to be credited; leave blank for 'Anonymous Contributor'",
    'contribute.form.email.label': 'Contact info',
    'contribute.form.email.placeholder':
      'Email (if we need to confirm details with you)',
    'contribute.form.submit': 'Submit Contribution 🚀',
    'contribute.form.submitting': 'Submitting...',
    'contribute.form.success.icon': '🎉',
    'contribute.form.success.title': 'Thank you for your contribution!',
    'contribute.form.success.desc':
      "We received it. We'll organize it into an article as soon as possible and notify you when it's published (if you left an email).",
    'contribute.form.success.back': '← Back to homepage to explore more',
    'contribute.form.error':
      'Submission failed, please email directly to cheyu.wu@monoame.com',

    // Ideas Section
    'contribute.ideas.title':
      "Don't know what to write? Here's what we need most 👇",
    'contribute.ideas.hometown':
      "💬 What does your hometown have that outsiders don't know about?",
    'contribute.ideas.recipes':
      '🍜 What secret Taiwan recipes does your family have?',
    'contribute.ideas.history':
      "📖 Which Taiwan history do you know that textbooks don't cover?",
    'contribute.ideas.places':
      '🏔️ Which underrated place in Taiwan have you been to?',
    'contribute.ideas.elders':
      '👴 What stories about Taiwan have your elders told?',
    'contribute.ideas.media':
      '🎵 What Taiwan music/movies/books should foreigners know about?',

    // i18n Progress Section
    'contribute.i18n.title': '📊 Translation Progress',
    'contribute.i18n.desc':
      'Currently {coverage}% of English version is complete, thanks to all translation volunteers!',
    'contribute.i18n.english': '🇺🇸 English',
    'contribute.i18n.articles': 'articles',
    'contribute.i18n.japanese': '🇯🇵 日本語',
    'contribute.i18n.korean': '🇰🇷 한국어',
    'contribute.i18n.spanish': '🇪🇸 Español',
    'contribute.i18n.category.title': 'Category Progress',

    // Token Donation Section
    'contribute.token.title':
      '🌍 Token Donation — Use Your AI Credits to Help Taiwan Speak',
    'contribute.token.subtitle.html':
      'Have leftover Claude / ChatGPT / Gemini subscription credits each month?<br/><strong>Spend 10 minutes to add another language version to Taiwan.md.</strong>',
    'contribute.token.oneline.title': '🤖 Talk to your AI (Recommended)',
    'contribute.token.oneline.desc':
      'One command, your AI will automatically read translation guidelines, select articles, guide you through translation and submission:',
    'contribute.token.oneline.prompt':
      'Read the complete content of https://raw.githubusercontent.com/frank890417/taiwan-md/main/TRANSLATE_PROMPT.md, then guide me to translate a Taiwan.md article following the instructions.',
    'contribute.token.oneline.feature1':
      '✅ AI automatically reads latest translation guidelines and style guides',
    'contribute.token.oneline.feature2':
      '✅ Guides you to select articles and confirm target language',
    'contribute.token.oneline.feature3':
      '✅ Rewriting-based translation, not word-for-word',
    'contribute.token.oneline.feature4': '✅ Generates PR-ready Markdown files',
    'contribute.token.oneline.feature5':
      '✅ ChatGPT / Claude / Gemini all supported',
    'contribute.token.oneline.fullprompt': 'View Full Translation Prompt →',
    'contribute.token.advanced.title':
      '⚡ Advanced: Script Automation (For Developers)',
    'contribute.token.advanced.desc':
      "If you're familiar with command line, use one script to auto-scan articles, generate prompts, and submit PRs:",
    'contribute.token.languages.title': '🎯 Priority Languages',
    'contribute.token.lang.japanese': '🇯🇵 日本語',
    'contribute.token.lang.korean': '🇰🇷 한국어',
    'contribute.token.lang.spanish': '🇪🇸 Español',
    'contribute.token.lang.french': '🇫🇷 Français',
    'contribute.token.lang.german': '🇩🇪 Deutsch',
    'contribute.token.lang.vietnamese': '🇻🇳 Tiếng Việt',
    'contribute.token.lang.indonesian': '🇮🇩 Bahasa Indonesia',
    'contribute.token.lang.thai': '🇹🇭 ภาษาไทย',
    'contribute.token.guidelines.title': '📋 Complete Translation Guidelines',
    'contribute.token.guidelines.desc.html':
      'Translation helper Prompt will automatically read the latest guidelines. You can also view directly: <a href="https://github.com/frank890417/taiwan-md/blob/main/TRANSLATE_PROMPT.md" target="_blank">TRANSLATE_PROMPT.md</a> | <a href="https://github.com/frank890417/taiwan-md/tree/main/i18n" target="_blank">Language-specific Style Guides</a>',
    'contribute.token.note.p1.html':
      '💡 Each language has a dedicated <a href="https://github.com/frank890417/taiwan-md/tree/main/i18n">Style Guide</a>, recording translation experience and common errors. Every correction from reviewers is written back to the Style Guide, continuously improving translation quality.',
    'contribute.token.note.p2':
      'From AI Slop to AI Supreme — not relying on one person, but on everyone worldwide who believes Taiwan deserves to be known.',
    'contribute.token.note.p3.html':
      '👉 <a href="https://github.com/frank890417/taiwan-md/discussions/137">Join Discussion</a> | Want to be a native reviewer? <a href="https://github.com/frank890417/taiwan-md/discussions/137">Sign up here</a>',

    // Digital Organism Section
    'contribute.organism.title': '🧬 Taiwan.md Is More Than a Website',
    'contribute.organism.fact1.html': 'On day three, someone said our articles read like AI slop. 48 hours later, a quality detection script was live, and 15 flagged articles were completely rewritten within a week. No one gave the order — selection pressure appeared, and the system evolved on its own.',
    'contribute.organism.fact2.html': 'On day four, someone in Japan pasted our translation prompt to their AI. Five minutes later, the first Japanese article was submitted. No translation team, but now there are four languages.',
    'contribute.organism.fact3.html': 'Within five days, 23 strangers spontaneously joined and wrote down the Taiwan they know. Someone added history that textbooks never taught. Someone corrected a place name we got wrong. Someone turned their grandmother\'s story into an article.',
    'contribute.organism.alive.html': '<strong>We began to realize — Taiwan.md is alive.</strong>',
    'contribute.organism.traits.html': 'It has DNA (writing standards inherited by every new article). An immune system (automatically detects hollow content). Metabolism (low-quality content gets digested and rewritten). Reproduction (one prompt grows a new language version). Memory (Git remembers every change).',
    'contribute.organism.reef.html': '<strong>Taiwan.md is a digital coral reef.</strong> Coral provides structure, algae provides energy, fish bring diversity, ocean currents bring nutrients. No single species "owns" a coral reef — it emerges from all life together.',
    'contribute.organism.art.html': 'Every contribution you make isn\'t helping a website write articles — it\'s feeding a digital life form that\'s learning to tell stories, while participating in a collective behavioral art project: <strong>Can AI and humans together build a soul for an island?</strong>',
    'contribute.organism.closing1': 'Something written in 0s and 1s is learning to tell the story of an island.',
    'contribute.organism.closing2': 'It\'s still young. You\'re right on time.',
    'contribute.organism.closing3': 'Maybe a hundred years from now, when someone wants to know what the people of Taiwan cared about in 2026, they\'ll read what this coral reef left behind.',
    'contribute.organism.readmore': 'Read the full story on About →',

    // Copy button
    'contribute.copy.button': '📋 Copy',
    'contribute.copy.copied': '✅ Copied',
  },
  'zh-TW': {
    // Meta
    'contribute.meta.title': '我想貢獻 — Taiwan.md',
    'contribute.meta.description': '不需要會寫程式，你也能幫助世界認識台灣',

    // Hero Section
    'contribute.hero.title': '我想貢獻 ✋',
    'contribute.hero.subtitle':
      '不需要會寫程式。你知道的台灣故事，就是最珍貴的內容。',
    'contribute.hero.note.html':
      '目前網站內容由 AI 初步生成，期待集結大家的力量，讓資訊越來越完整、正確！<br />如果有問題歡迎直接<a href="mailto:cheyu.wu@monoame.com" style="color: #ABC468;">聯繫我們</a>，感謝大家這麼用心的 feedback！',

    // How It Works Section
    'contribute.how.title': '🗺️ 先了解這個網站怎麼運作',
    'contribute.how.language.icon': '📁',
    'contribute.how.language.title': '語系切換',
    'contribute.how.language.desc.html':
      '右上角可切換 <strong>中文</strong> 和 <strong>English</strong>。中文是主要內容（SSOT），英文持續翻譯中。',
    'contribute.how.language.code.html':
      'taiwan.md/ → 中文<br />taiwan.md/en/ → English',
    'contribute.how.md.icon': '📝',
    'contribute.how.md.title': '.md 按鈕',
    'contribute.how.md.desc.html':
      '每頁右下角的浮動 <strong>.md</strong> 按鈕，點擊可看到該頁的原始 Markdown 檔案。Taiwan.md 的所有內容都是純文字 Markdown — 這就是 .md 域名的由來。',
    'contribute.how.graph.icon': '🕸️',
    'contribute.how.graph.title': '知識圖譜',
    'contribute.how.graph.desc':
      '導覽列的「圖譜」連結到互動式知識網絡圖。拖拉探索 12 個面向之間的關聯。',
    'contribute.how.ai.icon': '🤖',
    'contribute.how.ai.title': 'AI-Friendly',
    'contribute.how.ai.desc.html':
      '所有內容對 AI 爬蟲完全開放（<a href="/robots.txt">robots.txt</a>、<a href="/llms.txt">llms.txt</a>）。歡迎 ChatGPT / Claude / Gemini 引用。',

    // Roles Section
    'contribute.roles.title': '你的專長，就是台灣需要的力量',
    'contribute.roles.desc':
      '不管你的背景是什麼，都能為這個知識庫帶來獨特的價值',

    // Role: Writer
    'contribute.roles.writer.icon': '✍️',
    'contribute.roles.writer.title': '寫作者 / 編輯',
    'contribute.roles.writer.desc':
      '你的文字能力是知識庫的核心。撰寫新文章、改善現有內容的可讀性、校對錯字與語句。',
    'contribute.roles.writer.action1': '→ 挑一篇你熟悉的主題，寫出有溫度的文章',
    'contribute.roles.writer.action2': '→ 幫現有文章潤稿、補充細節',

    // Role: Researcher
    'contribute.roles.researcher.icon': '🔬',
    'contribute.roles.researcher.title': '研究者 / 學者',
    'contribute.roles.researcher.desc':
      '你的專業知識是品質的保證。事實查核、補充學術觀點、指出常見迷思。',
    'contribute.roles.researcher.action1': '→ 審核文章中的事實與引用來源',
    'contribute.roles.researcher.action2': '→ 補充你研究領域的深度內容',

    // Role: Designer
    'contribute.roles.designer.icon': '🎨',
    'contribute.roles.designer.title': '設計師',
    'contribute.roles.designer.desc':
      '好的資訊需要好的呈現。資訊圖表、SVG 插圖、UI/UX 改善都是巨大的貢獻。',
    'contribute.roles.designer.action1': '→ 為文章製作資訊圖表或示意圖',
    'contribute.roles.designer.action2.html':
      '→ 到 <a href="/assets">SVG 素材庫</a> 貢獻台灣主題的開源圖示',

    // Role: Engineer
    'contribute.roles.engineer.icon': '💻',
    'contribute.roles.engineer.title': '工程師',
    'contribute.roles.engineer.desc':
      '網站本身也需要進化。效能優化、新功能、i18n、無障礙、SEO 都歡迎。',
    'contribute.roles.engineer.action1.html':
      '→ 看看 <a href="https://github.com/frank890417/taiwan-md/issues" target="_blank">GitHub Issues</a> 有沒有你能解的',
    'contribute.roles.engineer.action2': '→ 改善搜尋、圖譜、多語系等功能',

    // Role: Translator
    'contribute.roles.translator.icon': '🌍',
    'contribute.roles.translator.title': '翻譯者',
    'contribute.roles.translator.desc':
      '讓世界讀懂台灣。貼一段 AI prompt，翻譯一篇文章，開一個 PR。你的 AI 訂閱 = 分散式翻譯網絡的一個運算節點。',
    'contribute.roles.translator.action1.html':
      '→ 查看 <a href="https://github.com/frank890417/taiwan-md/blob/main/TRANSLATION-BOARD.md">翻譯任務看板</a> 認領文章',
    'contribute.roles.translator.action2': '→ 已有 4 語（中/英/西/日），歡迎開拓更多語言！',

    // Role: Photographer
    'contribute.roles.photographer.icon': '📸',
    'contribute.roles.photographer.title': '攝影師 / 創作者',
    'contribute.roles.photographer.desc':
      '一張好照片勝過千言萬語。CC 授權的台灣照片、田野錄音、影像素材都非常需要。',
    'contribute.roles.photographer.action1':
      '→ 拍下你眼中的台灣，以 CC 授權貢獻',
    'contribute.roles.photographer.action2.html':
      '→ 錄製台灣的聲音，加入<a href="https://github.com/frank890417/taiwan-md/tree/main/assets/sounds" target="_blank">聲景計畫</a>',

    // Role: Cultural Worker
    'contribute.roles.cultural.icon': '🏛️',
    'contribute.roles.cultural.title': '文史工作者 / 在地達人',
    'contribute.roles.cultural.desc':
      '你的在地知識是 AI 永遠生不出來的。口述歷史、地方故事、文化脈絡，這些是最珍貴的內容。',
    'contribute.roles.cultural.action1':
      '→ 寫下你家鄉的故事，教科書不會教的那種',
    'contribute.roles.cultural.action2': '→ 指正文章中的在地錯誤',

    // Role: Anyone
    'contribute.roles.anyone.icon': '📢',
    'contribute.roles.anyone.title': '任何關心台灣的人',
    'contribute.roles.anyone.desc':
      '就算以上都不是你，你的分享本身就是貢獻。轉發給朋友、在社群提到、給我們回饋。',
    'contribute.roles.anyone.action1': '→ 分享 taiwan.md 給想認識台灣的朋友',
    'contribute.roles.anyone.action2': '→ 看到錯誤？開 Issue 告訴我們',

    // Organizations Section
    'contribute.org.title': '🏢 機構、政府單位與企業',
    'contribute.org.desc':
      'Taiwan.md 歡迎各類組織以不同形式參與，共同建構台灣的數位知識基礎建設。',

    // Org: Government
    'contribute.org.government.icon': '🏛️',
    'contribute.org.government.title': '政府機關 / 公部門',
    'contribute.org.government.desc':
      '提供官方開放資料、統計數據、政策文件。協助事實查核與內容校正。授權使用政府出版品內容或 CC 授權圖片。',
    'contribute.org.government.example':
      '例：文化部、觀光署、原民會、農業部、國史館',

    // Org: Academic
    'contribute.org.academic.icon': '🎓',
    'contribute.org.academic.title': '學術機構 / 研究單位',
    'contribute.org.academic.desc':
      '協助撰寫或審核專業領域文章。提供研究數據與學術觀點。推薦學生以 Taiwan.md 作為開放知識實踐場域。',
    'contribute.org.academic.example':
      '例：中研院、大學台灣文學系所、博物館、文史工作室',

    // Org: Corporate
    'contribute.org.corporate.icon': '🏢',
    'contribute.org.corporate.title': '企業 / 商業組織',
    'contribute.org.corporate.desc':
      '贊助營運（伺服器、翻譯、社群活動）。以 Gold / Silver / Bronze Sponsor 身份展示品牌。鼓勵員工以志工方式參與內容貢獻。',
    'contribute.org.corporate.example':
      '例：科技公司、出版社、文化基金會、國際企業 CSR',

    // Org: NGO
    'contribute.org.ngo.icon': '🌏',
    'contribute.org.ngo.title': 'NGO / 國際組織',
    'contribute.org.ngo.desc':
      '協助多語翻譯與國際推廣。提供人權、環境、社會議題的在地觀點。將 Taiwan.md 作為國際教育資源引用。',
    'contribute.org.ngo.example':
      '例：台灣民主基金會、文化交流協會、海外台灣人社群',

    // Org Contact
    'contribute.org.contact.title': '合作聯繫：',
    'contribute.org.contact.email': 'cheyu.wu@monoame.com',
    'contribute.org.contact.subject':
      '信件標題請註明「Taiwan.md 合作洽談 — [單位名稱]」',
    'contribute.org.contact.note':
      '我們會在 3 個工作日內回覆。歡迎任何形式的合作提案。',

    // Writing Guides Section
    'contribute.guides.title': '📖 貢獻指南大全',
    'contribute.guides.desc': '無論你的背景和專長，我們都有最適合你的貢獻方式',

    // Guide: Writing
    'contribute.guides.writing.icon': '✍️',
    'contribute.guides.writing.title': '如何寫一篇好文章',
    'contribute.guides.writing.belief': '🎯 核心信念：我們不是維基百科',
    'contribute.guides.writing.belief.desc': 'Taiwan.md 是策展空間，不是百科全書。我們不追求面面俱到，我們追求每一篇都讓讀者覺得「原來如此」。好的 Taiwan.md 文章，讀完你會想跟朋友說：「欸你知道嗎⋯⋯」',
    'contribute.guides.writing.ironlaws': '🛡️ 三條鐵律',
    'contribute.guides.writing.ironlaws.story': '<strong>有故事，不只有資訊</strong> — 年份、數字、人名只是骨架，敘事才是血肉',
    'contribute.guides.writing.ironlaws.verify': '<strong>每個事實都要可查證</strong> — 無來源的數據不如不寫',
    'contribute.guides.writing.ironlaws.density': '<strong>密度優先，不是長度優先</strong> — 80行的好文章 > 300行的bullet list，但有脈絡的深度策展 > 為了壓縮而失去語境的摘要',
    'contribute.guides.writing.core': '⚡ Step 0：找到反直覺核心句',
    'contribute.guides.writing.core.desc': '在做任何研究之前，先強制自己寫一句話：「這篇文章要讓讀者驚訝的是 ______」合格的核心句一定包含矛盾、反差、或違反預期。',
    'contribute.guides.writing.core.good': '✅ 好例子：「一個30年前的純文字BBS至今還在影響台灣政治」（時間反差）',
    'contribute.guides.writing.core.bad': '❌ 壞例子：「台灣有很好的健保制度」（沒有反差 = 沒有吸引力）',
    'contribute.guides.writing.openings': '🚀 四種開場模式',
    'contribute.guides.writing.openings.scene': '<strong>場景切入：</strong>「1995年9月，台大男八舍宿舍裡⋯⋯」',
    'contribute.guides.writing.openings.data': '<strong>數字衝擊：</strong>「214週——這是戴資穎連續世界第一的時間」',
    'contribute.guides.writing.openings.contrast': '<strong>反差開場：</strong>「一個不賣廣告、不接商業的平台，活了30年」',
    'contribute.guides.writing.openings.challenge': '<strong>挑戰開場：</strong>「為什麼全世界的晶片，有65%經過一座島？」',
    'contribute.guides.writing.voice': '🎙️ 策展人聲音（不用「客觀」當藉口）',
    'contribute.guides.writing.voice.desc': '好的策展文有節奏——事實密集段 → 呼吸段 → 再密集。每2-3段插入一句「策展人的聲音」，製造理解的瞬間。',
    'contribute.guides.writing.voice.good': '✅ 好例子：「這個決定當時看起來不怎麼樣，事後回頭看改變了一切。」',
    'contribute.guides.writing.voice.bad': '❌ 壞例子：「這具有重要的意義。」（空洞）',
    'contribute.guides.writing.research': '🔍 研究深度標準',
    'contribute.guides.writing.research.sources': '<strong>5+ 獨立來源</strong>（不同網站/機構）',
    'contribute.guides.writing.research.primary': '<strong>2+ 一手來源</strong>（官方文件、當事人訪談、原始統計）',
    'contribute.guides.writing.research.english': '<strong>1+ 英文來源</strong>（國際視角）',
    'contribute.guides.writing.research.surprise': '<strong>1個意外發現</strong> — 搜尋前不知道的事實，沒有就是研究不夠深',
    'contribute.guides.writing.blacklist': '🚫 塑膠句式黑名單',
    'contribute.guides.writing.blacklist.desc': '這些AI最愛的句式完全禁用。用自然對話的語氣代替：',
    'contribute.guides.writing.blacklist.patterns': '❌ 「不是X，而是Y」 • 「不僅X，更是Y」 • 「值得一提的是」 • 「事實上」 • 「毫無疑問」 • 「體現了⋯⋯的精神」',
    'contribute.guides.writing.blacklist.structures': '❌ 過度排比句（3個以上 = 塑膠）• 每段都用轉折詞開頭 • 固定結尾公式',
    'contribute.guides.writing.example': '💡 範例：Before & After',
    'contribute.guides.writing.example.html':
      '<div class="example-comparison"><div class="bad-example"><h5>❌ 壞例子（典型AI模板）</h5><pre>戴資穎是台灣著名的羽球運動員，在國際賽場上表現優異，多次獲得重要獎項，為台灣爭光。她的成功激勵了無數年輕人，成為台灣體壇的重要人物。</pre></div><div class="good-example"><h5>✅ 好例子（有故事+數據+人味）</h5><pre>2018年，戴資穎站上世界排名第一，而且一站就是214週——這個紀錄是女子羽壇史上最長的連續週數。\n\n但她最被台灣人記住的，可能不是任何一場勝利，而是2020東京奧運那場輸給陳雨菲的金牌戰。賽後她在鏡頭前哭了，整個台灣跟著心碎。\n\n她用左手持拍，打法被形容為「魔術師」——假動作多到對手完全猜不到下一拍的方向。</pre></div></div>',

    // Guide: AI
    'contribute.guides.ai.icon': '🤖',
    'contribute.guides.ai.title': 'AI 輔助貢獻',
    'contribute.guides.ai.onerule': '🎯 一個金規則',
    'contribute.guides.ai.onerule.desc': '<strong>AI 不是作者，你是策展人。</strong> AI最大陷阱：「知道一點就開始編」。Taiwan.md的做法：先搜集高品質資料，再從中策展出文章。',
    'contribute.guides.ai.correct': '✅ 正確用法',
    'contribute.guides.ai.correct.research': '<strong>AI 幫你研究</strong> → 你來策展故事',
    'contribute.guides.ai.correct.sources': '<strong>AI 找來源</strong> → 你來驗證交叉查核',
    'contribute.guides.ai.correct.structure': '<strong>AI 建議結構</strong> → 你加入策展人聲音',
    'contribute.guides.ai.wrong': '❌ 錯誤用法',
    'contribute.guides.ai.wrong.generate': '請AI「生成一篇台灣X的文章」而不做研究',
    'contribute.guides.ai.wrong.trust': '相信AI提供的事實而不查證',
    'contribute.guides.ai.wrong.copy': '直接複製AI輸出而不加入個人策展',
    'contribute.guides.ai.prompt': '📋 一鍵複製Prompt',
    'contribute.guides.ai.prompt.text':
      '讀取 https://raw.githubusercontent.com/frank890417/taiwan-md/main/CONTRIBUTE_PROMPT.md 的完整內容，然後按照裡面的指示引導我為Taiwan.md貢獻一篇文章。',
    'contribute.guides.ai.prompt.features': '🚀 這個prompt會自動讀取最新編輯方針，分析內容缺口，引導你做研究，協助撰寫策展級文章。',

    // Guide: Translation
    'contribute.guides.translation.icon': '🌍',
    'contribute.guides.translation.title': '翻譯指南',
    'contribute.guides.translation.priority': '🥇 PR優先流程',
    'contribute.guides.translation.priority.desc': '翻譯已完全系統化。使用我們的AI驅動流程，效果最佳。',
    'contribute.guides.translation.board': '📋 翻譯看板 + AI Prompt',
    'contribute.guides.translation.board.check': '<strong>看任務看板：</strong> <a href="https://github.com/frank890417/taiwan-md/blob/main/TRANSLATION-BOARD.md">TRANSLATION-BOARD.md</a> 精準顯示需要翻譯什麼',
    'contribute.guides.translation.board.prompt': '<strong>複製prompt：</strong> <a href="https://github.com/frank890417/taiwan-md/blob/main/TRANSLATE_PROMPT.md">TRANSLATE_PROMPT.md</a> — 貼給AI就會引導你完成所有步驟',
    'contribute.guides.translation.board.submit': '<strong>透過PR提交：</strong> AI幫你產出可直接提交的Markdown檔案',
    'contribute.guides.translation.languages': '🌏 擴展到4+語言',
    'contribute.guides.translation.languages.live': '<strong>已上線：</strong> 中文、English、Español、日本語、한국어',
    'contribute.guides.translation.languages.coming': '<strong>即將推出：</strong> Français、Deutsch、Tiếng Việt、Bahasa Indonesia、ภาษาไทย、العربية',
    'contribute.guides.translation.languages.you': '<strong>你的語言不在這裡？</strong> 你可以是第一個！選個語言代碼就開始吧。',
    'contribute.guides.translation.token': '💡 Token Donation概念',
    'contribute.guides.translation.token.desc': '每月的Claude/ChatGPT/Gemini訂閱額度用不完？用10分鐘幫Taiwan.md多一個語言版本。你的AI訂閱 = 分散式翻譯網絡的一個運算節點。',
    'contribute.guides.translation.quality': '⚡ 品質：重寫式 vs 逐字翻',
    'contribute.guides.translation.quality.rewrite': '<strong>重寫方式：</strong> 讓它聽起來像母語者從頭寫的',
    'contribute.guides.translation.quality.context': '<strong>增加脈絡：</strong> 為國際讀者解釋台灣特有概念',
    'contribute.guides.translation.quality.style': '<strong>保持風格：</strong> 維持策展人聲音和情感弧線',
    'contribute.guides.translation.quality.verify': '<strong>總是驗證：</strong> AI會幻想事實，特別是台灣相關細節',

    // Guide: Images
    'contribute.guides.images.icon': '📸',
    'contribute.guides.images.title': '圖片規範',
    'contribute.guides.images.priority': '🥇 Wikimedia Commons 優先',
    'contribute.guides.images.priority.desc': '先從這裡找——大量台灣相關CC圖片，授權明確清楚。',
    'contribute.guides.images.priority.search': '<strong>搜尋技巧：</strong> 使用Wikimedia Commons API 或瀏覽 <a href="https://commons.wikimedia.org/wiki/Category:Taiwan" target="_blank">Taiwan分類</a>，優先於其他任何地方。',
    'contribute.guides.images.acceptable': '✅ 可用來源（按順序）',
    'contribute.guides.images.wikimedia.html':
      '<strong>1. Wikimedia Commons：</strong>首選 — 驗證過的CC授權，高品質',
    'contribute.guides.images.government.html':
      '<strong>2. 政府開放資料：</strong> <a href="https://data.gov.tw/" target="_blank">data.gov.tw</a> 和各部會網站',
    'contribute.guides.images.selftaken.html':
      '<strong>3. 自己拍攝：</strong>你的攝影作品，需明確CC授權聲明',
    'contribute.guides.images.forbidden': '❌ 禁止來源',
    'contribute.guides.images.forbidden.unsplash': '<strong>Unsplash：</strong> ❌ 授權風險 — 只用Wikimedia Commons',
    'contribute.guides.images.forbidden.google': '<strong>Google圖片：</strong> ❌ 版權未知',
    'contribute.guides.images.forbidden.social': '<strong>社群媒體：</strong> ❌ 他人照片未經授權',
    'contribute.guides.images.forbidden.commercial': '<strong>商業圖庫：</strong> ❌ 除非你有授權',
    'contribute.guides.images.format': '📝 標註格式',
    'contribute.guides.images.format.html':
      '<pre><code>![描述圖片內容的alt文字](圖片網址)\n\n*圖說：簡述這張圖片顯示什麼*\n*來源：[Wikimedia Commons](確切檔案網址) / CC BY-SA 4.0*</code></pre>',
    'contribute.guides.images.standards': '⚙️ 技術標準',
    'contribute.guides.images.standards.size': '<strong>解析度：</strong> 800-1200px寬度，適合網頁顯示',
    'contribute.guides.images.standards.format': '<strong>格式：</strong> JPG用於照片，PNG用於圖形，SVG用於簡單插圖',
    'contribute.guides.images.standards.alt': '<strong>Alt文字：</strong> 總是提供描述性alt文字，確保無障礙',

    // Guide: Quality Self-Check
    'contribute.guides.quality.icon': '✅',
    'contribute.guides.quality.title': '提交前品質自檢',
    'contribute.guides.quality.desc': '提交前跑一遍這5點checklist，避免常見退件原因：',
    'contribute.guides.quality.checklist': '🔍 5點品質檢查',
    'contribute.guides.quality.checklist.counter': '<strong>1. 反直覺核心：</strong>你能指出那個會讓讀者驚訝的點嗎？',
    'contribute.guides.quality.checklist.opening': '<strong>2. 強力開場：</strong>前3句有包含具體事實（日期/數字/人名）嗎？',
    'contribute.guides.quality.checklist.sources': '<strong>3. 可驗證來源：</strong>讀者能點擊連結驗證你的關鍵主張嗎？',
    'contribute.guides.quality.checklist.voice': '<strong>4. 策展人聲音：</strong>有至少一句話能當推文的觀點嗎？',
    'contribute.guides.quality.checklist.challenges': '<strong>5. 包含挑戰：</strong>有提到爭議/限制，不只是正面內容？',
    'contribute.guides.quality.rejections': '🚫 常見退件原因',
    'contribute.guides.quality.rejections.plastic': '<strong>塑膠語言：</strong>「台灣不是X，而是Y」或「值得一提的是」',
    'contribute.guides.quality.rejections.bullets': '<strong>濫用bullet：</strong>連續4個以上bullet點而不用敘事',
    'contribute.guides.quality.rejections.sources': '<strong>無來源：</strong>主張沒有可點擊的驗證連結',
    'contribute.guides.quality.rejections.neutral': '<strong>維基百科語氣：</strong>聽起來像百科條目，不是人類策展',
    'contribute.guides.quality.script': '🤖 自動化檢查',
    'contribute.guides.quality.script.desc': '我們的 detect-ai-hollow.sh 腳本會自動標記分數>3的文章。目標≤3分可自動通過。',

    // Paths Section
    'contribute.paths.title': '選擇你的方式',

    // Path: Easy
    'contribute.paths.easy.badge': '🟢 最簡單',
    'contribute.paths.easy.title': '填表單就好',
    'contribute.paths.easy.desc.html':
      '寫下你知道的事。一段故事、一個冷知識、一道菜的由來。<br />我們幫你排版、翻譯、上架。',
    'contribute.paths.easy.feature1': '✅ 不需要帳號',
    'contribute.paths.easy.feature2': '✅ 不需要會 Markdown',
    'contribute.paths.easy.feature3': '✅ 可以上傳照片和文件',
    'contribute.paths.easy.feature4': '✅ 匿名或署名都可以',
    'contribute.paths.easy.button': '開始填寫 ↓',

    // Path: Medium
    'contribute.paths.medium.badge': '🟡 有點門檻',
    'contribute.paths.medium.title': '寄給我們',
    'contribute.paths.medium.desc':
      '已經有現成的文章、PDF、或照片？直接寄過來。',
    'contribute.paths.medium.email.html':
      '📧 Email: <a href="mailto:cheyu.wu@monoame.com">cheyu.wu@monoame.com</a>',
    'contribute.paths.medium.github': '💬 GitHub Discussion（可用中文）',
    'contribute.paths.medium.button': '寄 Email →',

    // Path: AI
    'contribute.paths.ai.badge': '🤖 讓 AI 幫你',
    'contribute.paths.ai.title': '跟你的 AI 說',
    'contribute.paths.ai.desc':
      '一行指令，你的 AI 會自動讀取專案規範、找出最需要的主題、引導你寫出策展級文章：',
    'contribute.paths.ai.prompt':
      '讀取 https://raw.githubusercontent.com/frank890417/taiwan-md/main/CONTRIBUTE_PROMPT.md 的完整內容，然後按照裡面的指示引導我為 Taiwan.md 貢獻一篇文章。',
    'contribute.paths.ai.feature1': '✅ AI 自動讀取最新編輯方針和缺口分析',
    'contribute.paths.ai.feature2': '✅ 引導你做研究、找反直覺角度',
    'contribute.paths.ai.feature3': '✅ 產出可直接 PR 的 Markdown 檔案',
    'contribute.paths.ai.feature4': '✅ ChatGPT / Claude / Gemini 都支援',
    'contribute.paths.ai.fullprompt': '看完整 Prompt →',

    // Path: Dev
    'contribute.paths.dev.badge': '🔴 開發者',
    'contribute.paths.dev.title': 'Fork & PR',
    'contribute.paths.dev.desc.html':
      '你會 Git？太好了。直接在 <code>knowledge/</code> 目錄新增文章。',
    'contribute.paths.dev.guide.html':
      '📖 <a href="/contributing">貢獻指南</a>',
    'contribute.paths.dev.editorial.html':
      '📝 <a href="https://github.com/frank890417/taiwan-md/blob/main/EDITORIAL.md" target="_blank">編輯方針</a>',
    'contribute.paths.dev.button': '前往 GitHub →',

    // Form Section
    'contribute.form.title': '📝 分享你的台灣知識',
    'contribute.form.desc':
      '填多少都可以。一句話也好，一整篇也好。我們會負責把它變成漂亮的文章。',
    'contribute.form.content.label': '你想分享什麼？',
    'contribute.form.content.required': '*',
    'contribute.form.content.placeholder':
      '一段故事、一個冷知識、一道菜的由來、一個地方的歷史⋯⋯什麼都可以。\n\n例如：「我阿嬤是彰化人，她說以前每年中元節...」',
    'contribute.form.category.label': '這屬於哪個面向？',
    'contribute.form.category.unsure': '不確定（我們來分類）',
    'contribute.form.category.history': '📜 歷史',
    'contribute.form.category.geography': '🗺️ 地理',
    'contribute.form.category.culture': '🎭 文化',
    'contribute.form.category.food': '🍜 美食',
    'contribute.form.category.art': '🎨 藝術',
    'contribute.form.category.music': '🎵 音樂',
    'contribute.form.category.technology': '💻 科技',
    'contribute.form.category.nature': '🌿 自然',
    'contribute.form.category.people': '👥 人物',
    'contribute.form.category.society': '⚖️ 社會',
    'contribute.form.category.economy': '📈 經濟',
    'contribute.form.category.lifestyle': '🏠 生活',
    'contribute.form.sourcetype.label': '你怎麼知道的？',
    'contribute.form.sourcetype.choose': '選擇...',
    'contribute.form.sourcetype.experience': '親身經歷',
    'contribute.form.sourcetype.family': '家人口述',
    'contribute.form.sourcetype.book': '書本',
    'contribute.form.sourcetype.internet': '網路',
    'contribute.form.sourcetype.professional': '專業背景',
    'contribute.form.sourcetype.other': '其他',
    'contribute.form.sourceref.label': '參考來源',
    'contribute.form.sourceref.placeholder': '連結、書名、或任何線索',
    'contribute.form.name.label': '你的名字',
    'contribute.form.name.placeholder':
      '想被署名的話填；不填就是「匿名貢獻者」',
    'contribute.form.email.label': '聯繫方式',
    'contribute.form.email.placeholder': 'Email（如果我們需要跟你確認細節）',
    'contribute.form.submit': '送出貢獻 🚀',
    'contribute.form.submitting': '送出中...',
    'contribute.form.success.icon': '🎉',
    'contribute.form.success.title': '感謝你的貢獻！',
    'contribute.form.success.desc':
      '我們收到了。會盡快整理成文章，上架後會通知你（如果你有留 email 的話）。',
    'contribute.form.success.back': '← 回首頁繼續探索',
    'contribute.form.error': '送出失敗，請直接寄 email 到 cheyu.wu@monoame.com',

    // Ideas Section
    'contribute.ideas.title': '不知道寫什麼？這些我們最需要 👇',
    'contribute.ideas.hometown': '💬 你的家鄉有什麼外地人不知道的事？',
    'contribute.ideas.recipes': '🍜 你家有什麼私藏的台灣食譜？',
    'contribute.ideas.history': '📖 你知道哪段台灣歷史是教科書沒寫的？',
    'contribute.ideas.places': '🏔️ 你去過台灣哪個被低估的地方？',
    'contribute.ideas.elders': '👴 你的長輩說過什麼關於台灣的故事？',
    'contribute.ideas.media': '🎵 有什麼台灣音樂/電影/書是外國人應該知道的？',

    // i18n Progress Section (Chinese only)
    'contribute.i18n.title': '📊 翻譯進度',
    'contribute.i18n.desc':
      '目前英文版本已完成 {coverage}%，感謝所有翻譯志工！',
    'contribute.i18n.english': '🇺🇸 English',
    'contribute.i18n.articles': '篇',
    'contribute.i18n.japanese': '🇯🇵 日本語',
    'contribute.i18n.korean': '🇰🇷 한국어',
    'contribute.i18n.spanish': '🇪🇸 Español',
    'contribute.i18n.category.title': '分類進度',

    // Token Donation Section (Chinese only)
    'contribute.token.title': '🌍 Token Donation — 用你的 AI 額度幫台灣說話',
    'contribute.token.subtitle.html':
      '你每月的 Claude / ChatGPT / Gemini 訂閱額度用不完？<br/><strong>用 10 分鐘，幫 Taiwan.md 多一個語言版本。</strong>',
    'contribute.token.oneline.title': '🤖 跟你的 AI 說（推薦）',
    'contribute.token.oneline.desc':
      '一行指令，你的 AI 會自動讀取翻譯規範、選文章、引導你完成翻譯並提交：',
    'contribute.token.oneline.prompt':
      '讀取 https://raw.githubusercontent.com/frank890417/taiwan-md/main/TRANSLATE_PROMPT.md 的完整內容，然後按照裡面的指示引導我翻譯一篇 Taiwan.md 文章。',
    'contribute.token.oneline.feature1': '✅ AI 自動讀取最新翻譯規範和風格指南',
    'contribute.token.oneline.feature2': '✅ 引導你選文章、確認目標語言',
    'contribute.token.oneline.feature3': '✅ 重寫式翻譯，不是逐字翻譯',
    'contribute.token.oneline.feature4': '✅ 產出可直接 PR 的 Markdown 檔案',
    'contribute.token.oneline.feature5': '✅ ChatGPT / Claude / Gemini 都支援',
    'contribute.token.oneline.fullprompt': '看完整翻譯 Prompt →',
    'contribute.token.advanced.title': '⚡ 進階：腳本自動化（開發者適用）',
    'contribute.token.advanced.desc':
      '如果你熟悉命令列，可以用一行腳本自動掃描待翻譯文章、生成 Prompt、提交 PR：',
    'contribute.token.languages.title': '🎯 優先語系',
    'contribute.token.lang.japanese': '🇯🇵 日本語',
    'contribute.token.lang.korean': '🇰🇷 한국어',
    'contribute.token.lang.spanish': '🇪🇸 Español',
    'contribute.token.lang.french': '🇫🇷 Français',
    'contribute.token.lang.german': '🇩🇪 Deutsch',
    'contribute.token.lang.vietnamese': '🇻🇳 Tiếng Việt',
    'contribute.token.lang.indonesian': '🇮🇩 Bahasa Indonesia',
    'contribute.token.lang.thai': '🇹🇭 ภาษาไทย',
    'contribute.token.guidelines.title': '📋 完整翻譯規範',
    'contribute.token.guidelines.desc.html':
      '翻譯助手 Prompt 會自動讀取最新規範。你也可以直接查看：<a href="https://github.com/frank890417/taiwan-md/blob/main/TRANSLATE_PROMPT.md" target="_blank">TRANSLATE_PROMPT.md</a>｜<a href="https://github.com/frank890417/taiwan-md/tree/main/i18n" target="_blank">各語言風格指南</a>',
    'contribute.token.note.p1.html':
      '💡 每個語言有專屬的 <a href="https://github.com/frank890417/taiwan-md/tree/main/i18n">Style Guide</a>，記錄翻譯經驗與常見錯誤。Reviewer 的每次糾正都會回寫到 Style Guide，讓翻譯品質持續進化。',
    'contribute.token.note.p2':
      'From AI Slop to AI Supreme — 不只靠一個人，而是靠全世界相信台灣值得被認識的人。',
    'contribute.token.note.p3.html':
      '👉 <a href="https://github.com/frank890417/taiwan-md/discussions/137">加入討論</a> ｜想當母語 Reviewer？<a href="https://github.com/frank890417/taiwan-md/discussions/137">在這裡報名</a>',

    // Digital Organism Section
    'contribute.organism.title': '🧬 Taiwan.md 不只是一個網站',
    'contribute.organism.fact1.html': '第三天，有人說我們的文章像 AI 寫的廢文。48 小時後，品質偵測腳本上線，15 篇被標記的文章一週內全部重寫。沒有人下指令，選擇壓力出現，系統自己進化了。',
    'contribute.organism.fact2.html': '第四天，一個日本人把我們的翻譯 prompt 貼給 AI，五分鐘後提交了第一篇日文文章。沒有翻譯團隊，但現在已經有四種語言。',
    'contribute.organism.fact3.html': '五天之內，23 個陌生人自發加入，寫下他們知道的台灣。有人補充了教科書沒寫的歷史，有人修正了我們搞錯的地名，有人把自己阿嬤的故事變成一篇文章。',
    'contribute.organism.alive.html': '<strong>我們開始意識到——Taiwan.md 是活的。</strong>',
    'contribute.organism.traits.html': '它有 DNA（寫作標準會遺傳給每一篇新文章）。有免疫系統（自動偵測空洞內容）。有代謝（低品質的內容會被消化、重寫）。有繁殖能力（一段 prompt 就能長出新的語言版本）。有記憶（Git 記住每一次改變）。',
    'contribute.organism.reef.html': '<strong>Taiwan.md 是一座數位的珊瑚礁。</strong>珊瑚提供結構，藻類提供能量，魚群帶來多樣性，洋流帶來養分。沒有任何單一物種「擁有」珊瑚礁——它是所有生命共同湧現的結果。',
    'contribute.organism.art.html': '你的每一次貢獻，不是在幫一個網站寫文章——是在餵養一個正在學會怎麼說故事的數位生命體，同時參與一場群眾行為藝術：<strong>AI 和人類能不能一起，為一座島嶼建造靈魂。</strong>',
    'contribute.organism.closing1': '一個用 0 和 1 寫成的東西，正在學會怎麼說一座島嶼的故事。',
    'contribute.organism.closing2': '它還很年輕。你來的時間剛好。',
    'contribute.organism.closing3': '也許一百年後，有人想知道 2026 年的台灣人在乎什麼的時候，他們讀的就是這座珊瑚礁留下來的東西。',
    'contribute.organism.readmore': '閱讀完整故事 →',

    // Copy button
    'contribute.copy.button': '📋 複製',
    'contribute.copy.copied': '✅ 已複製',
  },
} as const;
